/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RssDotxmlRouteImport } from './routes/rss[.]xml'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InvestmentsIndexRouteImport } from './routes/investments/index'
import { Route as ExpensesIndexRouteImport } from './routes/expenses/index'
import { Route as InvestmentsGlidePathsIndexRouteImport } from './routes/investments/glide-paths/index'
import { Route as InvestmentsAllocationsIndexRouteImport } from './routes/investments/allocations/index'
import { Route as InvestmentsAccountsIndexRouteImport } from './routes/investments/accounts/index'
import { Route as ExpensesCategoriesIndexRouteImport } from './routes/expenses/categories/index'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RssDotxmlRoute = RssDotxmlRouteImport.update({
  id: '/rss.xml',
  path: '/rss.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestmentsIndexRoute = InvestmentsIndexRouteImport.update({
  id: '/investments/',
  path: '/investments/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpensesIndexRoute = ExpensesIndexRouteImport.update({
  id: '/expenses/',
  path: '/expenses/',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestmentsGlidePathsIndexRoute =
  InvestmentsGlidePathsIndexRouteImport.update({
    id: '/investments/glide-paths/',
    path: '/investments/glide-paths/',
    getParentRoute: () => rootRouteImport,
  } as any)
const InvestmentsAllocationsIndexRoute =
  InvestmentsAllocationsIndexRouteImport.update({
    id: '/investments/allocations/',
    path: '/investments/allocations/',
    getParentRoute: () => rootRouteImport,
  } as any)
const InvestmentsAccountsIndexRoute =
  InvestmentsAccountsIndexRouteImport.update({
    id: '/investments/accounts/',
    path: '/investments/accounts/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ExpensesCategoriesIndexRoute = ExpensesCategoriesIndexRouteImport.update({
  id: '/expenses/categories/',
  path: '/expenses/categories/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/settings': typeof SettingsRoute
  '/expenses/': typeof ExpensesIndexRoute
  '/investments/': typeof InvestmentsIndexRoute
  '/expenses/categories/': typeof ExpensesCategoriesIndexRoute
  '/investments/accounts/': typeof InvestmentsAccountsIndexRoute
  '/investments/allocations/': typeof InvestmentsAllocationsIndexRoute
  '/investments/glide-paths/': typeof InvestmentsGlidePathsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/settings': typeof SettingsRoute
  '/expenses': typeof ExpensesIndexRoute
  '/investments': typeof InvestmentsIndexRoute
  '/expenses/categories': typeof ExpensesCategoriesIndexRoute
  '/investments/accounts': typeof InvestmentsAccountsIndexRoute
  '/investments/allocations': typeof InvestmentsAllocationsIndexRoute
  '/investments/glide-paths': typeof InvestmentsGlidePathsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/settings': typeof SettingsRoute
  '/expenses/': typeof ExpensesIndexRoute
  '/investments/': typeof InvestmentsIndexRoute
  '/expenses/categories/': typeof ExpensesCategoriesIndexRoute
  '/investments/accounts/': typeof InvestmentsAccountsIndexRoute
  '/investments/allocations/': typeof InvestmentsAllocationsIndexRoute
  '/investments/glide-paths/': typeof InvestmentsGlidePathsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/rss.xml'
    | '/settings'
    | '/expenses/'
    | '/investments/'
    | '/expenses/categories/'
    | '/investments/accounts/'
    | '/investments/allocations/'
    | '/investments/glide-paths/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/rss.xml'
    | '/settings'
    | '/expenses'
    | '/investments'
    | '/expenses/categories'
    | '/investments/accounts'
    | '/investments/allocations'
    | '/investments/glide-paths'
  id:
    | '__root__'
    | '/'
    | '/rss.xml'
    | '/settings'
    | '/expenses/'
    | '/investments/'
    | '/expenses/categories/'
    | '/investments/accounts/'
    | '/investments/allocations/'
    | '/investments/glide-paths/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RssDotxmlRoute: typeof RssDotxmlRoute
  SettingsRoute: typeof SettingsRoute
  ExpensesIndexRoute: typeof ExpensesIndexRoute
  InvestmentsIndexRoute: typeof InvestmentsIndexRoute
  ExpensesCategoriesIndexRoute: typeof ExpensesCategoriesIndexRoute
  InvestmentsAccountsIndexRoute: typeof InvestmentsAccountsIndexRoute
  InvestmentsAllocationsIndexRoute: typeof InvestmentsAllocationsIndexRoute
  InvestmentsGlidePathsIndexRoute: typeof InvestmentsGlidePathsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rss.xml': {
      id: '/rss.xml'
      path: '/rss.xml'
      fullPath: '/rss.xml'
      preLoaderRoute: typeof RssDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investments/': {
      id: '/investments/'
      path: '/investments'
      fullPath: '/investments/'
      preLoaderRoute: typeof InvestmentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expenses/': {
      id: '/expenses/'
      path: '/expenses'
      fullPath: '/expenses/'
      preLoaderRoute: typeof ExpensesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investments/glide-paths/': {
      id: '/investments/glide-paths/'
      path: '/investments/glide-paths'
      fullPath: '/investments/glide-paths/'
      preLoaderRoute: typeof InvestmentsGlidePathsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investments/allocations/': {
      id: '/investments/allocations/'
      path: '/investments/allocations'
      fullPath: '/investments/allocations/'
      preLoaderRoute: typeof InvestmentsAllocationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investments/accounts/': {
      id: '/investments/accounts/'
      path: '/investments/accounts'
      fullPath: '/investments/accounts/'
      preLoaderRoute: typeof InvestmentsAccountsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expenses/categories/': {
      id: '/expenses/categories/'
      path: '/expenses/categories'
      fullPath: '/expenses/categories/'
      preLoaderRoute: typeof ExpensesCategoriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RssDotxmlRoute: RssDotxmlRoute,
  SettingsRoute: SettingsRoute,
  ExpensesIndexRoute: ExpensesIndexRoute,
  InvestmentsIndexRoute: InvestmentsIndexRoute,
  ExpensesCategoriesIndexRoute: ExpensesCategoriesIndexRoute,
  InvestmentsAccountsIndexRoute: InvestmentsAccountsIndexRoute,
  InvestmentsAllocationsIndexRoute: InvestmentsAllocationsIndexRoute,
  InvestmentsGlidePathsIndexRoute: InvestmentsGlidePathsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
